#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail

OUT_DIR="dist"
NAME=""
VERSION=""
TARGET_TRIPLE=""
SBOM_CVE_DB=""
BINARY_CVE_DB=""
SEED_DIR=""
ARTIFACT_DIR=""
SIGN_KEY="bhf-dist-root"
LEGACY_SIGN_KEY_EXPLICIT=0
SIGNING_KEY=""
KEY_ID=""
TRUSTED_PUBLIC_KEY=""
LEGACY_INTEGRITY_ONLY=0
SKIP_BUILD=0
DRY_RUN=0
GENERATE_SBOM_CVE_DB=0
GENERATE_BINARY_CVE_DB=0
GENERATE_SEED_DIR=0

usage() {
  cat <<'EOF'
Usage: scripts/package-offline-dist.sh [options]

Build a binary-only BHF distribution tarball. The tarball includes
release binaries, harness runtime support files, an authenticated content pack
(or explicitly requested unauthenticated legacy pack),
install.sh, bhf-bug-report, INSTALL.md, LICENSE, README.md,
RELEASE_NOTES.md, README-DIST.md, RUN-BHF.md, RECOMMENDED-SWEEP.md,
AUTO-OFFLINE-RUNBOOK.md, and a tiny pre-activation smoke
fixture.
It does not include BHF source.

Options:
  --out DIR               Output directory for staged dist, tar.gz, .sig, and hashes (default: dist)
  --name NAME             Distribution directory/archive basename
  --version VERSION       Version label for VERSION file and content pack
  --target-triple TRIPLE  Target triple label (default: rustc host triple)
  --sbom-cve-db FILE      BHF SBOM CVE DB JSON to bundle
                          (default: generate dist/content-inputs/sbom-cves.json)
  --binary-cve-db FILE    BHF binary-scan CVE DB JSON to bundle
                          (default: generate dist/content-inputs/binary-cves.json)
  --seed-dir DIR          Seed corpus directory to archive into the content pack
                          (default: generate dist/content-inputs/seeds)
  --artifact-dir DIR      Directory containing prebuilt bhf, daemon, and
                          Linux shim artifacts; implies --skip-build
  --signing-key FILE      Ed25519 PKCS#8 v2 private key kept outside the package
  --key-id ID             Publisher key ID for --signing-key
  --trusted-public-key FILE  Raw 64-character public key hex for producer self-check;
                          never treated as installer trust or bundled as policy
  --legacy-integrity-only Explicitly create an unauthenticated checksum-only pack
  --sign-key KEY          Deprecated digest label for legacy mode (default: bhf-dist-root)
  --allow-empty-cve-db    Compatibility no-op; omitted DBs are generated by default
  --skip-build            Reuse target/release artifacts instead of cargo build
  --dry-run               Print major actions without executing build/package commands
  -h, --help              Show this help

Build-machine example:
  scripts/package-offline-dist.sh --signing-key /secure/publisher.der \
    --key-id publisher-v1 --trusted-public-key /secure/publisher.pub

Destination-machine example:
  tar xzf dist/bhf-dist-<version>-<triple>.tar.gz
  cd bhf-dist-<version>-<triple>
  ./install.sh --trust-policy /path/from/trusted-channel/policy.json

Authenticate the whole tarball and verifier out of band before executing install.sh.
The content pack signature alone does not authenticate this installer.
EOF
}

die() {
  printf 'package-offline-dist.sh: %s\n' "$*" >&2
  exit 1
}

quote_cmd() {
  local first=1
  local arg
  for arg in "$@"; do
    if [[ "$first" -eq 0 ]]; then
      printf ' '
    fi
    printf '%q' "$arg"
    first=0
  done
  printf '\n'
}

run() {
  printf '+ '
  quote_cmd "$@"
  if [[ "$DRY_RUN" -eq 0 ]]; then
    "$@"
  fi
}

sanitize_label() {
  printf '%s' "$1" | sed -E 's/[^A-Za-z0-9._-]+/-/g; s/^-+//; s/-+$//'
}

copy_tree() {
  local src="$1"
  local dst="$2"
  [[ -e "$src" ]] || die "missing required path: $src"
  run mkdir -p "$(dirname "$dst")"
  run rm -rf "$dst"
  run cp -a "$src" "$dst"
}

resolve_output_dir() {
  local dir="$1"
  case "$dir" in
    /*) printf '%s' "$dir" ;;
    *) printf '%s/%s' "$REPO_ROOT" "$dir" ;;
  esac
}

write_default_content_inputs() {
  local input_root="$1"
  if [[ "$GENERATE_SBOM_CVE_DB" -eq 1 || "$GENERATE_BINARY_CVE_DB" -eq 1 || "$GENERATE_SEED_DIR" -eq 1 ]]; then
    run mkdir -p "$input_root"
  fi
  if [[ "$GENERATE_SBOM_CVE_DB" -eq 1 ]]; then
    if [[ "$DRY_RUN" -eq 0 && ! -f "$SBOM_CVE_DB" ]]; then
      write_empty_sbom_cve_db "$SBOM_CVE_DB"
    fi
    printf 'SBOM CVE DB: %s\n' "$SBOM_CVE_DB"
  fi
  if [[ "$GENERATE_BINARY_CVE_DB" -eq 1 ]]; then
    if [[ "$DRY_RUN" -eq 0 && ! -f "$BINARY_CVE_DB" ]]; then
      write_empty_binary_cve_db "$BINARY_CVE_DB"
    fi
    printf 'Binary CVE DB: %s\n' "$BINARY_CVE_DB"
  fi
  if [[ "$GENERATE_SEED_DIR" -eq 1 ]]; then
    run mkdir -p "$SEED_DIR"
    printf 'Seed corpus directory: %s\n' "$SEED_DIR"
  fi
}

write_empty_sbom_cve_db() {
  local out="$1"
  cat >"$out" <<'JSON'
{
  "schema_version": "bhf.cve_db.v1",
  "vulnerabilities": []
}
JSON
}

write_empty_binary_cve_db() {
  local out="$1"
  cat >"$out" <<'JSON'
{
  "schema_version": "bhf.binary.cves.v1",
  "components": []
}
JSON
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --out)
      [[ $# -ge 2 ]] || die "--out requires a directory"
      OUT_DIR="$2"
      shift 2
      ;;
    --name)
      [[ $# -ge 2 ]] || die "--name requires a value"
      NAME="$2"
      shift 2
      ;;
    --version)
      [[ $# -ge 2 ]] || die "--version requires a value"
      VERSION="$2"
      shift 2
      ;;
    --target-triple)
      [[ $# -ge 2 ]] || die "--target-triple requires a value"
      TARGET_TRIPLE="$2"
      shift 2
      ;;
    --sbom-cve-db)
      [[ $# -ge 2 ]] || die "--sbom-cve-db requires a file"
      SBOM_CVE_DB="$2"
      shift 2
      ;;
    --binary-cve-db)
      [[ $# -ge 2 ]] || die "--binary-cve-db requires a file"
      BINARY_CVE_DB="$2"
      shift 2
      ;;
    --seed-dir)
      [[ $# -ge 2 ]] || die "--seed-dir requires a directory"
      SEED_DIR="$2"
      shift 2
      ;;
    --artifact-dir)
      [[ $# -ge 2 ]] || die "--artifact-dir requires a directory"
      ARTIFACT_DIR="$2"
      SKIP_BUILD=1
      shift 2
      ;;
    --sign-key)
      [[ $# -ge 2 ]] || die "--sign-key requires a value"
      SIGN_KEY="$2"
      LEGACY_SIGN_KEY_EXPLICIT=1
      shift 2
      ;;
    --signing-key)
      [[ $# -ge 2 ]] || die "--signing-key requires a file"
      SIGNING_KEY="$2"
      shift 2
      ;;
    --key-id)
      [[ $# -ge 2 ]] || die "--key-id requires a value"
      KEY_ID="$2"
      shift 2
      ;;
    --trusted-public-key)
      [[ $# -ge 2 ]] || die "--trusted-public-key requires a file"
      TRUSTED_PUBLIC_KEY="$2"
      shift 2
      ;;
    --legacy-integrity-only)
      LEGACY_INTEGRITY_ONLY=1
      shift
      ;;
    --allow-empty-cve-db)
      shift
      ;;
    --skip-build)
      SKIP_BUILD=1
      shift
      ;;
    --dry-run)
      DRY_RUN=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      die "unknown option '$1'"
      ;;
  esac
done

if [[ "$LEGACY_INTEGRITY_ONLY" -eq 1 ]]; then
  [[ -z "$SIGNING_KEY" && -z "$KEY_ID" && -z "$TRUSTED_PUBLIC_KEY" ]] \
    || die "--legacy-integrity-only cannot be combined with signing options"
  printf 'package-offline-dist.sh: warning: legacy content pack is checksum-only and does not authenticate a publisher\n' >&2
else
  [[ "$LEGACY_SIGN_KEY_EXPLICIT" -eq 0 ]] || die "--sign-key is only valid with --legacy-integrity-only"
  [[ -n "$SIGNING_KEY" && -n "$KEY_ID" && -n "$TRUSTED_PUBLIC_KEY" ]] \
    || die "authenticated packaging requires --signing-key, --key-id, and --trusted-public-key (or explicitly --legacy-integrity-only)"
  [[ "$KEY_ID" =~ ^[A-Za-z0-9._-]+$ ]] || die "invalid --key-id"
  [[ -f "$SIGNING_KEY" ]] || die "--signing-key file not found"
  [[ -f "$TRUSTED_PUBLIC_KEY" ]] || die "--trusted-public-key file not found: $TRUSTED_PUBLIC_KEY"
  PUBLIC_HEX="$(tr -d '\r\n' <"$TRUSTED_PUBLIC_KEY")"
  [[ "$PUBLIC_HEX" =~ ^[0-9a-f]{64}$ ]] || die "--trusted-public-key must contain 64 lowercase hex characters"
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd -P)"

if [[ -z "$VERSION" ]]; then
  if git -C "$REPO_ROOT" rev-parse --git-dir >/dev/null 2>&1; then
    VERSION="$(git -C "$REPO_ROOT" describe --tags --always --dirty)"
  else
    VERSION="$(date +%Y%m%d)"
  fi
fi
VERSION="$(sanitize_label "$VERSION")"

if [[ -z "$TARGET_TRIPLE" ]]; then
  TARGET_TRIPLE="$(rustc -vV | awk '/^host:/ {print $2}')"
fi
TARGET_TRIPLE="$(sanitize_label "$TARGET_TRIPLE")"

if [[ -z "$NAME" ]]; then
  NAME="bhf-dist-${VERSION}-${TARGET_TRIPLE}"
fi
NAME="$(sanitize_label "$NAME")"
case "$NAME" in
  ""|.|..) die "unsafe distribution name '$NAME'" ;;
esac

OUT_ROOT="$(resolve_output_dir "$OUT_DIR")"
if [[ "$LEGACY_INTEGRITY_ONLY" -eq 0 ]]; then
  command -v readlink >/dev/null 2>&1 || die "readlink is required to guard signing-key location"
  SIGNING_KEY_CANONICAL="$(readlink -f -- "$SIGNING_KEY")"
  OUT_ROOT_CANONICAL="$(readlink -m -- "$OUT_ROOT")"
  case "$SIGNING_KEY_CANONICAL" in
    "$OUT_ROOT_CANONICAL"|"$OUT_ROOT_CANONICAL"/*)
      die "--signing-key must be outside the distribution output directory" ;;
  esac
fi
CONTENT_INPUT_ROOT="$OUT_ROOT/content-inputs"
if [[ -z "$SBOM_CVE_DB" ]]; then
  SBOM_CVE_DB="$CONTENT_INPUT_ROOT/sbom-cves.json"
  GENERATE_SBOM_CVE_DB=1
fi
if [[ -z "$BINARY_CVE_DB" ]]; then
  BINARY_CVE_DB="$CONTENT_INPUT_ROOT/binary-cves.json"
  GENERATE_BINARY_CVE_DB=1
fi
if [[ -z "$SEED_DIR" ]]; then
  SEED_DIR="$CONTENT_INPUT_ROOT/seeds"
  GENERATE_SEED_DIR=1
fi

write_default_content_inputs "$CONTENT_INPUT_ROOT"

if [[ -n "$SBOM_CVE_DB" && ! -f "$SBOM_CVE_DB" ]]; then
  if [[ "$DRY_RUN" -eq 0 || "$GENERATE_SBOM_CVE_DB" -eq 0 ]]; then
    die "--sbom-cve-db file not found: $SBOM_CVE_DB"
  fi
fi
if [[ -n "$BINARY_CVE_DB" && ! -f "$BINARY_CVE_DB" ]]; then
  if [[ "$DRY_RUN" -eq 0 || "$GENERATE_BINARY_CVE_DB" -eq 0 ]]; then
    die "--binary-cve-db file not found: $BINARY_CVE_DB"
  fi
fi
if [[ -n "$SEED_DIR" && ! -d "$SEED_DIR" ]]; then
  if [[ "$DRY_RUN" -eq 0 || "$GENERATE_SEED_DIR" -eq 0 ]]; then
    die "--seed-dir directory not found: $SEED_DIR"
  fi
fi

cd "$REPO_ROOT"

if [[ "$SKIP_BUILD" -eq 0 ]]; then
  run cargo build --release --workspace
fi

if [[ -n "$ARTIFACT_DIR" ]]; then
  case "$ARTIFACT_DIR" in
    /*) TARGET_DIR="$ARTIFACT_DIR" ;;
    *) TARGET_DIR="$REPO_ROOT/$ARTIFACT_DIR" ;;
  esac
else
  TARGET_DIR="$REPO_ROOT/target/release"
fi
BHF_BIN="$TARGET_DIR/bhf"
DAEMON_BIN="$TARGET_DIR/bhf-daemon"
SHIM_DIST="$TARGET_DIR/libbhf_runtrace.so"
SHIM_CANONICAL="$TARGET_DIR/libbhf_runtrace_shim.so"
CC_INTERCEPT="$TARGET_DIR/libbhf_cc_intercept.so"

if [[ "$DRY_RUN" -eq 0 ]]; then
  [[ -x "$BHF_BIN" ]] || die "missing release binary: $BHF_BIN"
  [[ -x "$DAEMON_BIN" ]] || die "missing release binary: $DAEMON_BIN"
  if [[ ! -f "$SHIM_DIST" && ! -f "$SHIM_CANONICAL" ]]; then
    die "missing runtrace shim beside release binaries"
  fi
  [[ -f "$CC_INTERCEPT" ]] || die "missing compiler-interception shim: $CC_INTERCEPT"
fi

STAGE_ROOT="$OUT_ROOT/$NAME"
TOOL_DIR="$STAGE_ROOT/tool"
CONTENT_ROOT="$STAGE_ROOT/content"
PACK_ROOT="$CONTENT_ROOT/packs/current"
TARBALL="$OUT_ROOT/${NAME}.tar.gz"
if [[ "$LEGACY_INTEGRITY_ONLY" -eq 1 && ( -e "${TARBALL}.sig" || -e "${TARBALL}.sig.sha256" ) ]]; then
  die "stale detached signature assets exist for legacy archive"
fi

run rm -rf "$STAGE_ROOT"
run mkdir -p "$TOOL_DIR" "$PACK_ROOT/rules" "$PACK_ROOT/cve" "$PACK_ROOT/corpus"

run cp "$BHF_BIN" "$TOOL_DIR/bhf"
run cp "$DAEMON_BIN" "$TOOL_DIR/bhf-daemon"
if [[ -f "$SHIM_DIST" ]]; then
  run cp "$SHIM_DIST" "$TOOL_DIR/libbhf_runtrace.so"
fi
if [[ -f "$SHIM_CANONICAL" ]]; then
  run cp "$SHIM_CANONICAL" "$TOOL_DIR/libbhf_runtrace_shim.so"
fi
run cp "$CC_INTERCEPT" "$TOOL_DIR/libbhf_cc_intercept.so"
run cp "$SCRIPT_DIR/bhf-bug-report.sh" "$TOOL_DIR/bhf-bug-report"
run chmod +x "$TOOL_DIR/bhf-bug-report"

copy_tree "$REPO_ROOT/c_runtime" "$TOOL_DIR/c_runtime"
copy_tree "$REPO_ROOT/ada_runtime" "$TOOL_DIR/ada_runtime"
run rm -rf "$TOOL_DIR/ada_runtime/obj" "$TOOL_DIR/ada_runtime/lib"
run find "$TOOL_DIR/ada_runtime" -type f \( -name '*.o' -o -name '*.ali' -o -name '*.stdout' -o -name '*.stderr' -o -name '*.lexch' \) -delete
copy_tree "$REPO_ROOT/java_runtime" "$TOOL_DIR/java_runtime"
copy_tree "$REPO_ROOT/python_runtime" "$TOOL_DIR/python_runtime"
run find "$TOOL_DIR/python_runtime" -type d -name __pycache__ -prune -exec rm -rf {} +
copy_tree "$REPO_ROOT/perl_runtime" "$TOOL_DIR/perl_runtime"
copy_tree "$REPO_ROOT/crates/rust_runtime" "$TOOL_DIR/crates/rust_runtime"
copy_tree "$REPO_ROOT/csharp_runtime" "$TOOL_DIR/csharp_runtime"
copy_tree "$REPO_ROOT/js_runtime" "$TOOL_DIR/js_runtime"
copy_tree "$REPO_ROOT/ruby_runtime" "$TOOL_DIR/ruby_runtime"
copy_tree "$REPO_ROOT/lua_runtime" "$TOOL_DIR/lua_runtime"
copy_tree "$REPO_ROOT/php_runtime" "$TOOL_DIR/php_runtime"

run cp "$SCRIPT_DIR/install-dist.sh" "$STAGE_ROOT/install.sh"
run chmod +x "$STAGE_ROOT/install.sh"
run cp "$REPO_ROOT/INSTALL.md" "$STAGE_ROOT/INSTALL.md"
run cp "$REPO_ROOT/LICENSE" "$STAGE_ROOT/LICENSE"
run cp "$REPO_ROOT/README.md" "$STAGE_ROOT/README.md"
run cp "$REPO_ROOT/RELEASE_NOTES.md" "$STAGE_ROOT/RELEASE_NOTES.md"
run cp "$REPO_ROOT/docs/site/offline-auto-runbook.md" "$STAGE_ROOT/AUTO-OFFLINE-RUNBOOK.md"
run cp "$REPO_ROOT/docs/recommended-sweep.md" "$STAGE_ROOT/RECOMMENDED-SWEEP.md"
run mkdir -p "$TOOL_DIR/docs"
run cp "$REPO_ROOT/docs/site/offline-auto-runbook.md" "$TOOL_DIR/docs/AUTO-OFFLINE-RUNBOOK.md"
run cp "$REPO_ROOT/docs/recommended-sweep.md" "$TOOL_DIR/docs/RECOMMENDED-SWEEP.md"

run mkdir -p "$STAGE_ROOT/smoke/c"
if [[ "$DRY_RUN" -eq 0 ]]; then
  cat >"$STAGE_ROOT/smoke/c/bhf_smoke.c" <<'EOF'
// SPDX-License-Identifier: Apache-2.0
#include <stddef.h>

int bhf_smoke_parse(const unsigned char *data, size_t len) {
    if (len >= 4 && data[0] == 'G' && data[1] == 'F' && data[2] == 'Z') {
        return data[3] == '!';
    }
    return 0;
}
EOF
fi

if [[ "$DRY_RUN" -eq 0 ]]; then
  cat >"$STAGE_ROOT/VERSION" <<EOF
name=$NAME
version=$VERSION
target_triple=$TARGET_TRIPLE
built_at=$(date -u +%Y-%m-%dT%H:%M:%SZ)
commit=$(git -C "$REPO_ROOT" rev-parse HEAD 2>/dev/null || printf unknown)
EOF

  cat >"$STAGE_ROOT/README-DIST.md" <<'EOF'
# BHF Distribution

This is the all-in-one Linux package. It contains the BHF CLI and daemon,
both Linux preload shims, harness runtime support files, a tiny pre-activation
smoke fixture, a privacy-scrubbing bug-report collector, and a content
pack (authenticated unless the producer explicitly selected legacy mode).
`INSTALL.md`, `LICENSE`, `README.md`, and `RELEASE_NOTES.md` are included
at the archive root as the standard installation, licensing, usage, and release
documentation, alongside `RUN-BHF.md` (running it after install),
`RECOMMENDED-SWEEP.md` (the one command to start with and how to size every
flag), and `AUTO-OFFLINE-RUNBOOK.md` (broken or incomplete Ada/C/C++ drops).

Install or update:

```sh
./install.sh --trust-policy /path/from/trusted-channel/policy.json
```

Authenticate the **whole distribution archive and installer/verifier** through
an independent trusted channel before running bundle code. The public key or
policy shipped in the same unverified archive would not establish trust.
For explicitly produced legacy checksum-only packs, use
`--allow-legacy-integrity-only` instead of `--trust-policy`; this does not
authenticate the publisher.

Re-running `install.sh` from a newer package **updates** an existing install in
place — you do not uninstall first. It stages and validates the new files,
then moves the old prefix to a backup and the stage into place. It **replaces**
the binaries + runtime trees, **preserves** your `<prefix>/packs/` and
`<prefix>/corpora/`, and **backs
up** the previous install to `<prefix>.backup.<timestamp>` (roll back with `mv`).
Your run outputs under any `--work-dir` live outside the prefix and are never
touched.

The installer can also be run non-interactively:

```sh
./install.sh --non-interactive [options]
```

Installer options:

```text
--prefix DIR            Install prefix (default: /opt/bhf)
--bin-dir DIR           Directory for bhf symlinks (default: /usr/local/bin)
--non-interactive       Do not prompt; use selected or default profiles
--languages LIST        Comma list: c,cpp,rust,java,python,perl,go,ada,cobol,
                        fortran,csharp,javascript,typescript,ruby,lua,php,all,none
--targets LIST          Comma list: native,windows,aarch64,all,none
--fuzzers LIST          Comma list: builtin,afl,all,none
--extras LIST           Comma list: build-recovery,sandbox,archives,all,none
--install-seeds         Extract bundled seed corpus into <prefix>/corpora/seeds
--package-manager NAME  System package manager: auto, apt-get, dnf, yum, none
                        (default: auto)
--no-system-packages    Skip system package installation
--no-apt                Compatibility alias for --no-system-packages
--no-rustup             Skip rustup installation and nightly toolchain setup
--trust-policy FILE     Externally provisioned publisher public-key policy
--allow-legacy-integrity-only  Permit checksum-only, unauthenticated content
--no-content            Skip content pack verify/install
--no-symlink            Do not create bhf symlinks in --bin-dir
--no-smoke              Skip the pre-activation bhf auto smoke test
--smoke-work-dir DIR    Work directory for the pre-activation smoke test
--dry-run               Print commands without executing them
-h, --help              Show installer help
```

Multiple-selection example:

```sh
./install.sh --non-interactive \
  --prefix /opt/bhf \
  --languages c,cpp,rust \
  --targets native,aarch64 \
  --fuzzers builtin,afl \
  --extras build-recovery,archives
```

Full install example:

```sh
./install.sh --non-interactive \
  --languages all \
  --targets all \
  --fuzzers all \
  --extras all \
  --install-seeds
```

`--languages all` means all sixteen fuzzing lanes. With no language option, the
installer keeps the original eight core lanes selected and offers COBOL,
Fortran, C#, JavaScript, TypeScript, Ruby, Lua, and PHP as opt-ins. The C# lane
requires a separately staged .NET 8 SDK and `SharpFuzz.CommandLine`; TypeScript
requires `esbuild` on `PATH` or already installed in the target project.

The installer detects Debian/Ubuntu (`apt-get`) and RHEL-family
(`dnf`/`yum`) hosts automatically. On RHEL, packages absent from the enabled
repositories are reported per lane while available core dependencies continue
to install. Use `--package-manager` to override detection.

The bundled content pack lives under `content/packs/current` and is verified
against the external trust policy before any package-manager or prefix change.

This `install.sh` bundle is the simplest complete Linux install. The release
also publishes separate `.tar.xz` component archives for operators who prefer
to manually co-locate only selected files. See `INSTALL.md` for that alternative.

If BHF itself errors on your source tree (an internal panic, or a harness its
own codegen left broken), it records a boiled-down bug report at
`<work-dir>/auto/bug-report.md` (+ `.json`) instead of only crashing, and keeps
sweeping past the bad file. Run with `--debug` to capture a backtrace per panic:

```sh
bhf auto --debug <source-tree> --work-dir bhf_work
```

Send `bug-report.md` (or one entry from it) to the maintainer — it carries the
bhf version/commit, the file/target, and the backtrace needed to fix it.

For build/harness failures on a running or completed campaign, create a compact
support report instead of collecting ad hoc commands by hand:

```sh
bhf-bug-report /path/to/bhf_work
```

The collector reads structured result checkpoints, so it works before the sweep
finishes. It includes outcome/error counts, representative diagnostic shapes,
repair-ledger health, artifact presence, and local toolchain versions. It never
includes source or generated harness text, and replaces paths, file names,
targets, variables, types, Ada units, symbols, and macros before writing the
size-capped `bhf-support-report.txt`.

For running BHF after installation, see `RUN-BHF.md`. For the strongest
offline Ada/C/C++ recovery commands, including known-build, unknown-build, and
forced fallback variants, see `AUTO-OFFLINE-RUNBOOK.md`. The installer also
places that runbook at `<prefix>/docs/AUTO-OFFLINE-RUNBOOK.md`.
EOF

  cat >"$STAGE_ROOT/RUN-BHF.md" <<'EOF'
<!-- SPDX-License-Identifier: Apache-2.0 -->

# Running BHF

This guide is for operators using this binary-only BHF distribution after
`install.sh` has installed it.

## Installed Layout

The default install prefix is `/opt/bhf`. Unless you passed different
installer options, the installer copies the CLI, daemon, runtrace shim, and
harness runtime files there, then creates `bhf` and `bhf-daemon`
symlinks in `/usr/local/bin`.

Useful locations:

- `/opt/bhf/bhf` - CLI binary
- `/opt/bhf/bhf-daemon` - JSON-RPC/read-only-MCP daemon for IDE and agent integrations
- `/opt/bhf/libbhf_runtrace.so` - LD_PRELOAD runtime shim
- `/opt/bhf/libbhf_cc_intercept.so` - compiler-interception shim for complex C/C++ build recovery
- `/opt/bhf/bhf-bug-report` - compact privacy-scrubbed support-report collector
- `/opt/bhf/packs/` - installed offline content packs
- `/opt/bhf/corpora/seeds/` - bundled seeds when installed with
  `--install-seeds`
- `VERSION` - package name, version, target triple, build time, and commit

Run this first:

```sh
bhf --help
```

If you installed without symlinks, call `/opt/bhf/bhf` directly or add
`/opt/bhf` to `PATH`.

## Smoke Test

The installer runs the bundled C smoke fixture by default. To rerun it from the
extracted distribution directory:

```sh
# --per-target-time is in seconds; 5 means 5 seconds per discovered target.
bhf auto smoke/c --work-dir /tmp/bhf-smoke --per-target-time 5 --verbose
```

The smoke run proves discovery, harness generation, build, fuzz execution, and
report rendering for the C lane. It requires `clang` and `make`.

## Run an Automatic Sweep

For most source drops, use `bhf auto`. It discovers targets, ranks them,
generates harnesses, repairs build gaps where possible, fuzzes, and writes
reports. This is the recommended command — `RECOMMENDED-SWEEP.md` in this
distribution explains how to size every flag, and `bhf auto --help` prints
the same command at the end:

```sh
bhf auto /path/to/source-tree \
  --work-dir bhf_work \
  --jobs 4 \
  --per-target-time 60 \
  --campaign-time 3600 \
  --max-targets 40 \
  --unsafe-search-and-run-build-commands \
  --force \
  --static \
  --sbom \
  --sloc sloc.txt \
  --debug
```

`--unsafe-search-and-run-build-commands` EXECUTES the scanned tree's own build
to recover its real compile flags. Use it only on sources you trust; without it
BHF still recovers what it can from `compile_commands.json` and its probes.

For a smaller first look, drop `--sbom` and use `--per-target-time 5
--max-targets 10`:

```sh
# --per-target-time is in seconds; 30 means 30 seconds per discovered target.
bhf auto /path/to/source-tree \
  --work-dir bhf_work \
  --per-target-time 30 \
  --verbose
```

`auto` recognizes all sixteen source lanes: Ada, C, C++, Rust, Java, Python,
Perl, Go, COBOL, Fortran, C#, JavaScript, TypeScript, Ruby, Lua, and PHP.

Useful options:

- `--languages c,cpp,ada,csharp,javascript` limits the sweep to selected lanes;
  omit it to use every lane found in the tree.
- `--max-targets 25` runs only the highest ranked targets.
- `--campaign-time 3600` caps the whole run at 3600 seconds, which is one hour.
  This is the whole-campaign maximum time; use it when you want the sweep to
  stop starting new targets after a fixed wall-clock budget.
- `--target NAME`, `--harness-id ID`, or `--target-file PATH` reruns a narrower
  slice.
- `--engine builtin,afl++` runs both engines for native C/C++ targets when AFL++
  is installed.
- `--sbom` writes SBOM, CycloneDX, vulnerability, VEX, and CSV artifacts at the
  end of the sweep.
- `--debug` captures a backtrace for any bhf-internal panic and enriches the
  bug report (see "When BHF itself errors" below).

Missing language toolchains are reported as skipped or failed build lanes; they
do not require network access. Install only the toolchains for the languages you
intend to fuzz.

For broken or incomplete Ada/C/C++ source drops, see
`AUTO-OFFLINE-RUNBOOK.md` in this distribution. It gives the strongest
known-build and unknown-build commands, explains which recovery flags combine,
and keeps the `--force` fallback in a separate evidence bucket. After install,
the same file is available at `/opt/bhf/docs/AUTO-OFFLINE-RUNBOOK.md` when
the default prefix is used.

## Read Results

The main outputs are under the work directory:

- `auto/summary.txt` - outcome summary, throughput, coverage, and artifact paths
- `auto/run.md` - human-readable report
- `auto/run.json` - machine-readable report
- `auto/bug-report.md` / `auto/bug-report.json` - BHF's OWN internal defects,
  written only when BHF itself panicked or a codegen bug occurred (see below)
- `findings/` - saved crashing or policy-relevant test cases
- `harnesses/` and `build/` - generated harnesses and compiled outputs
- `sbom/` - supply-chain outputs when `--sbom` is used

Start with:

```sh
less bhf_work/auto/run.md
```

To report a BHF build/harness limitation without exposing project names or
typing many one-off command results, run this while the campaign is running or
after it completes:

```sh
bhf-bug-report /path/to/bhf_work
```

It writes and prints one size-capped `bhf-support-report.txt`. The report is
derived from per-target structured checkpoints; it omits source, harnesses, and
corpus inputs and replaces project paths and identifiers with typed placeholders.

Use `auto/run.json` for CI ingestion, dashboards, and repeatable triage.

## When BHF itself errors: `--debug` and the bug report

If BHF *itself* fails on your tree — an internal panic, or a harness its own
codegen left broken — it records that as a bug report instead of only crashing,
and keeps sweeping past the bad file. This is distinct from findings (bugs in
your target) and from `missing-deps.txt` (dependencies your environment lacks):
the bug report is BHF's OWN defects, boiled down to what a maintainer needs.

- A BHF-internal panic while parsing or fuzzing ONE file is caught at that
  file/target boundary — the run records it and continues instead of aborting.
- When a run hits any internal defect, BHF writes
  `<work-dir>/auto/bug-report.json` and `bug-report.md` and prints a one-line
  pointer. A clean run writes neither.

Add `--debug` to capture a backtrace per panic (it sets `RUST_BACKTRACE` for
you), which pins the exact source line:

```sh
bhf auto --debug /path/to/source-tree --work-dir bhf_work
# → bhf_work/auto/bug-report.md
```

`bug-report.md` lists each issue with its category (`PANIC` / `codegen`), the
source file and target, the language, the BHF version + commit, and (under
`--debug`) the backtrace. Send that file — or a single entry — to get the defect
fixed; it carries everything needed to reproduce.

## Updating this install (data-safe)

Re-running `install.sh` from a newer package updates this install in place; you
do not uninstall first. It stages and validates before replacing the prefix.
It **replaces** the binaries + runtime trees, **preserves** `<prefix>/packs/` and
`<prefix>/corpora/`, and **backs up** the previous install to
`<prefix>.backup.<timestamp>` (roll back with `mv`). Your run outputs under any
`--work-dir` live outside the prefix and are never touched. See `README-DIST.md`
for the full update walkthrough.

## Generate Reports and CSV

`bhf auto` writes the primary run report automatically:

- `bhf_work/auto/run.md` - human-readable campaign report
- `bhf_work/auto/run.json` - machine-readable campaign report
- `bhf_work/auto/findings.csv` - one row per root-cause finding group

To render a separate findings report bundle from saved findings, use
`bhf report`. This is useful when you want spreadsheet, SARIF, or JUnit
outputs for triage, CI, or compliance systems:

```sh
bhf report \
  --findings bhf_work/findings \
  --out bhf_work/reports \
  --run last \
  --csv \
  --sarif \
  --junit
```

That command writes:

- `bhf_work/reports/last.md`
- `bhf_work/reports/last.json`
- `bhf_work/reports/last.csv`
- `bhf_work/reports/last.sarif`
- `bhf_work/reports/last.junit.xml`

For supply-chain reporting, `bhf auto --sbom` writes SBOM artifacts at the
end of the sweep. You can also generate them directly from a source tree or work
directory:

```sh
bhf sbom /path/to/source-tree \
  --out bhf_work/sbom \
  --emit sbom,cyclonedx,vulnerabilities,openvex,csv
```

That command writes JSON SBOM/VEX/vulnerability artifacts plus CSV projections:

- `bhf_work/sbom/sbom.json`
- `bhf_work/sbom/cyclonedx.json`
- `bhf_work/sbom/vulnerabilities.json`
- `bhf_work/sbom/openvex.json`
- `bhf_work/sbom/sbom.csv`
- `bhf_work/sbom/vulnerabilities.csv`

If you installed a real offline CVE database in a content pack, pass it with
`--vuln-db /opt/bhf/packs/<pack-id>/cve/sbom-cves.json`. Without a CVE
database, SBOM inventory still works, but vulnerability match outputs are empty.

## Fuzz and Replay a Specific Harness

`bhf auto` is the normal entry point, but you can continue fuzzing a built
harness directly:

```sh
# --time accepts duration suffixes; 10m means 10 minutes.
bhf fuzz bhf_work --harness H-EXAMPLE --time 10m --seed-input smoke
```

Replay a finding from a report:

```sh
bhf replay --finding bhf_work/findings/F-0001
```

If automatic harness resolution cannot find the binary, pass it explicitly:

```sh
bhf replay --finding bhf_work/findings/F-0001 \
  --harness bhf_work/build/H-EXAMPLE/main
```

## Runtime Shim

The shim is armed for native Ada, C, C++, Rust, Go, COBOL, and Fortran runs plus
Python, Perl, Ruby, Lua, and PHP interpreter processes. If the CLI cannot find
the shim automatically, point it at the installed copy:

```sh
export BHF_RUNTRACE_SHIM=/opt/bhf/libbhf_runtrace.so
```

Java, C#, JavaScript, and TypeScript fuzzing do not load the LD_PRELOAD shim
because interposing their managed runtime processes would mostly observe the
launcher/runtime rather than target behavior. Cross-compiled and emulated runs
also leave it disabled.

## Daemon and IDE Use

`bhf-daemon` is installed for IDE thin clients, JSON-RPC integrations, and
five read-only MCP tools. Run the daemon from the installed prefix or through
the symlink configured by the installer:

```sh
bhf-daemon
# MCP stdio transport for an approved local agent host:
bhf-daemon --mcp
```

Use the CLI for batch and CI jobs. Use default daemon mode when an editor owns
BHF sessions, or `--mcp` for read-only static scan, target ranking, harness
preflight, report summary, and finding lookup. MCP does not build or fuzz.

## Offline Content

The installer verifies and installs the content pack from
`content/packs/current`. Installed packs live under `/opt/bhf/packs/`.

A content pack is an offline bundle of BHF data with SHA-256 payload checks and,
in authenticated mode, an Ed25519 signature verified against an independently
provisioned public key. A legacy digest alone does not authenticate its publisher. This distribution
uses it for the built-in rule catalog, offline CVE databases, and optional seed
corpora. Bundle a content pack when the destination machine cannot fetch updates
from the network, when you need a repeatable evidence trail for exactly which
rules and vulnerability data were used, or when you want to move customer- or
program-specific corpora through the same verified install path as the tool.

To inspect or verify a pack manually:

```sh
bhf pack verify content/packs/current/update-pack.json \
  --root content/packs/current \
  --policy /path/from/trusted-channel/policy.json --require-authenticated
```

If you installed bundled seeds with `--install-seeds`, pass them into a run with:

Seeds are example input files that initialize the fuzz corpus before mutation
starts. Good seeds are valid or nearly-valid messages, files, packets, records,
or API payloads for the target parser. Installing seeds is useful because it can
reach format gates faster, preserve known-good regression inputs, and share a
common starting corpus across offline machines.

```sh
bhf auto /path/to/source-tree \
  --work-dir bhf_work \
  --seed-dir /opt/bhf/corpora/seeds
```
EOF
fi

if [[ "$DRY_RUN" -eq 0 ]]; then
  "$BHF_BIN" rules list --json >"$PACK_ROOT/rules/static.json"
  cp "$SBOM_CVE_DB" "$PACK_ROOT/cve/sbom-cves.json"
  cp "$BINARY_CVE_DB" "$PACK_ROOT/cve/binary-cves.json"
  tar -C "$SEED_DIR" -czf "$PACK_ROOT/corpus/seeds.tar.gz" .
fi

if [[ "$DRY_RUN" -eq 0 ]]; then
  cat >"$CONTENT_ROOT/bhf-policy.json" <<EOF
{
  "schema_version": "bhf.policy.v1",
  "policy_id": "bhf-dist",
  "version": "$VERSION",
  "rules": {
    "enabled": [],
    "disabled": []
  },
  "update_packs": {
    "allowed_kinds": ["rules", "cve", "corpus"]
  }
}
EOF
fi

PACK_ID="bhf-content-$VERSION"
PACK_CREATE=("$BHF_BIN" pack create \
  --root "$PACK_ROOT" \
  --pack-id "$PACK_ID" \
  --version "$VERSION" \
  --item rules:rules/static.json \
  --item cve:cve/sbom-cves.json \
  --item cve:cve/binary-cves.json \
  --item corpus:corpus/seeds.tar.gz)
if [[ "$LEGACY_INTEGRITY_ONLY" -eq 1 ]]; then
  PACK_CREATE+=(--sign-key "$SIGN_KEY")
else
  PACK_CREATE+=(--signing-key "$SIGNING_KEY" --key-id "$KEY_ID")
fi
PACK_CREATE+=(--out "$PACK_ROOT/update-pack.json")
if [[ "$LEGACY_INTEGRITY_ONLY" -eq 1 ]]; then
  run "${PACK_CREATE[@]}"
else
  printf '+ %q pack create [items omitted] --signing-key [redacted] --key-id %q --out %q\n' \
    "$BHF_BIN" "$KEY_ID" "$PACK_ROOT/update-pack.json"
  if [[ "$DRY_RUN" -eq 0 ]]; then
    "${PACK_CREATE[@]}"
  fi
fi

if [[ "$LEGACY_INTEGRITY_ONLY" -eq 1 ]]; then
  run "$BHF_BIN" pack verify "$PACK_ROOT/update-pack.json" \
    --root "$PACK_ROOT" --policy "$CONTENT_ROOT/bhf-policy.json"
else
  PRODUCER_CHECK_POLICY="$OUT_ROOT/${NAME}.publisher-check-policy.json"
  if [[ "$DRY_RUN" -eq 0 ]]; then
    cat >"$PRODUCER_CHECK_POLICY" <<EOF
{"update_packs":{"require_signature":true,"trusted_public_keys":{"$KEY_ID":"$PUBLIC_HEX"}}}
EOF
  fi
  run "$BHF_BIN" pack verify "$PACK_ROOT/update-pack.json" \
    --root "$PACK_ROOT" --policy "$PRODUCER_CHECK_POLICY" --require-authenticated
fi

run tar -C "$OUT_ROOT" -czf "$TARBALL" "$NAME"
if [[ "$LEGACY_INTEGRITY_ONLY" -eq 0 ]]; then
  run command -v openssl
  if [[ "$DRY_RUN" -eq 0 ]]; then
    "$BHF_BIN" pack sign-archive --archive "$TARBALL" \
      --signing-key "$SIGNING_KEY" --out "${TARBALL}.sig"
    bash "$SCRIPT_DIR/verify-offline-dist.sh" --archive "$TARBALL" \
      --signature "${TARBALL}.sig" --trusted-public-key "$TRUSTED_PUBLIC_KEY"
    (cd "$OUT_ROOT" && sha256sum "${NAME}.tar.gz.sig" >"${NAME}.tar.gz.sig.sha256")
  else
    printf '+ %q pack sign-archive --archive %q --signing-key [redacted] --out %q\n' \
      "$BHF_BIN" "$TARBALL" "${TARBALL}.sig"
    printf '+ bash %q --archive %q --signature %q --trusted-public-key [path redacted]\n' \
      "$SCRIPT_DIR/verify-offline-dist.sh" "$TARBALL" "${TARBALL}.sig"
  fi
fi
run sha256sum "$TARBALL"
if [[ "$DRY_RUN" -eq 0 ]]; then
  (cd "$OUT_ROOT" && sha256sum "${NAME}.tar.gz" >"${NAME}.tar.gz.sha256")
fi

printf 'Distribution archive: %s\n' "$TARBALL"
printf 'Checksum: %s.sha256\n' "$TARBALL"
if [[ "$LEGACY_INTEGRITY_ONLY" -eq 0 ]]; then
  printf 'Detached Ed25519 signature: %s.sig\n' "$TARBALL"
  printf 'Signature checksum: %s.sig.sha256\n' "$TARBALL"
fi
